# Random Forest Model 

In [205]:
# libraries!
import numpy as np      
import pandas as pd    
from IPython.display import display


In [206]:
# Read in the data 
filename = '../CleanedData/AllData5Bins5000.csv'
all_data = pd.read_csv(filename)      
print(f"{filename} : file read into a pandas dataframe.")

../CleanedData/AllData5Bins5000.csv : file read into a pandas dataframe.


In [207]:
# Visualize the data 
print(f"df_tidy.shape is {all_data.shape}\n")
all_data.info()  # prints column information

display(all_data)

df_tidy.shape is (6300, 18)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6300 entries, 0 to 6299
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Holiday               6300 non-null   int64  
 1   ETo (in)              6300 non-null   float64
 2   Precip (in)           6300 non-null   float64
 3   Sol Rad (Ly/day)      6300 non-null   int64  
 4   Avg Vap Pres (mBars)  6300 non-null   float64
 5   Max Air Temp (F)      6300 non-null   float64
 6   Min Air Temp (F)      6300 non-null   float64
 7   Avg Air Temp (F)      6300 non-null   float64
 8   Max Rel Hum (%)       6300 non-null   int64  
 9   Min Rel Hum (%)       6300 non-null   int64  
 10  Avg Rel Hum (%)       6300 non-null   int64  
 11  Dew Point (F)         6300 non-null   float64
 12  Avg Wind Speed (mph)  6300 non-null   float64
 13  Wind Run (miles)      6300 non-null   float64
 14  Avg Soil Temp (F)     6300 non-null   float

Holiday  ETo (in)  Precip (in)  Sol Rad (Ly/day)  Avg Vap Pres (mBars)  \
0           0      0.19         0.00               470                  13.2   
1           0      0.20         0.00               478                  12.8   
2           0      0.19         0.00               463                  12.7   
3           0      0.20         0.00               465                  11.4   
4           1      0.19         0.00               479                  11.9   
...       ...       ...          ...               ...                   ...   
6295        0      0.06         0.07               265                   6.1   
6296        0      0.11         0.00               445                   4.0   
6297        0      0.13         0.01               446                   4.0   
6298        0      0.14         0.00               438                   3.5   
6299        0      0.15         0.00               463                   3.3   

      Max Air Temp (F)  Min Air Temp (F)  Avg Air Temp (F)  Max Rel Hum (%)  \
0                 93.5              60.6              76.0               76   
1                 92.5              59.2              75.8               75   
2                 92.2              61.0              76.1               67   
3                 94.4              61.2              76.7               61   
4                 90.7              58.3              74.1               65   
...                ...               ...               ...              ...   
6295              50.6              34.9              42.9               90   
6296              58.1              30.2              43.9               71   
6297              64.2              33.2              48.8               67   
6298              68.2              34.4              51.6               54   
6299              75.4              36.9              55.1               49   

      Min Rel Hum (%)  Avg Rel Hum (%)  Dew Point (F)  Avg Wind Speed (mph)  \
0                  21               43           52.0                   3.1   
1                  21               42           51.1                   3.3   
2                  22               41           50.9                   3.0   
3                  16               36           47.9                   3.1   
4                  20               41           49.0                   3.0   
...               ...              ...            ...                   ...   
6295               37               65           31.8                   3.8   
6296               18               41           21.7                   3.0   
6297               16               34           21.6                   3.4   
6298               13               27           18.5                   3.2   
6299                8               22           17.2                   3.4   

      Wind Run (miles)  Avg Soil Temp (F)  DayOfWeek  ZoneNum  Consumption  
0                 75.2               73.2          0        0            0  
1                 79.4               73.2          1        0            0  
2                 73.1               73.0          2        0            0  
3                 73.4               73.0          3        0            0  
4                 73.1               72.1          4        0            0  
...                ...                ...        ...      ...          ...  
6295              92.0               52.7          2       11           47  
6296              72.2               51.4          3       11           49  
6297              82.6               51.5          4       11           53  
6298              76.5               51.6          5       11           55  
6299              80.8               52.0          6       11           61  

[6300 rows x 18 columns]

In [208]:

COLUMNS = all_data.columns            # "list" of columns

# let's create a dictionary to look up any column index by name
COL_INDEX = {}
for i, name in enumerate(COLUMNS):
    COL_INDEX[name] = i  # using the name (as key), look up the value (i)
print(f"COL_INDEX is {COL_INDEX}\n\n")

ClassNames = []

for num in range(104):
    ClassNames += [str(num)]

COL_INDEX is {'Holiday': 0, 'ETo (in)': 1, 'Precip (in)': 2, 'Sol Rad (Ly/day)': 3, 'Avg Vap Pres (mBars)': 4, 'Max Air Temp (F)': 5, 'Min Air Temp (F)': 6, 'Avg Air Temp (F)': 7, 'Max Rel Hum (%)': 8, 'Min Rel Hum (%)': 9, 'Avg Rel Hum (%)': 10, 'Dew Point (F)': 11, 'Avg Wind Speed (mph)': 12, 'Wind Run (miles)': 13, 'Avg Soil Temp (F)': 14, 'DayOfWeek': 15, 'ZoneNum': 16, 'Consumption': 17}




In [209]:
# Convert to array
A = all_data.to_numpy()   
print(A)

[[0.0e+00 1.9e-01 0.0e+00 ... 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 2.0e-01 0.0e+00 ... 1.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 1.9e-01 0.0e+00 ... 2.0e+00 0.0e+00 0.0e+00]
 ...
 [0.0e+00 1.3e-01 1.0e-02 ... 4.0e+00 1.1e+01 5.3e+01]
 [0.0e+00 1.4e-01 0.0e+00 ... 5.0e+00 1.1e+01 5.5e+01]
 [0.0e+00 1.5e-01 0.0e+00 ... 6.0e+00 1.1e+01 6.1e+01]]


In [210]:
# Convert to float
A = A.astype('float64')  
print(A)

[[0.0e+00 1.9e-01 0.0e+00 ... 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 2.0e-01 0.0e+00 ... 1.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 1.9e-01 0.0e+00 ... 2.0e+00 0.0e+00 0.0e+00]
 ...
 [0.0e+00 1.3e-01 1.0e-02 ... 4.0e+00 1.1e+01 5.3e+01]
 [0.0e+00 1.4e-01 0.0e+00 ... 5.0e+00 1.1e+01 5.5e+01]
 [0.0e+00 1.5e-01 0.0e+00 ... 6.0e+00 1.1e+01 6.1e+01]]


In [211]:
# Get the num of rows and columns
NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


The dataset has 6300 rows and 18 cols


In [212]:
print("+++ Start of data definitions +++\n")

X_all = A[:,0:NUM_COLS-1]  # X (features) 
y_all = A[:,NUM_COLS-1]    # y (labels)

+++ Start of data definitions +++



In [213]:
# Scramble the data to remove (potential) dependence on its ordering: 

indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_permed = X_all[indices]              
y_permed = y_all[indices]              
print(f"The scrambled labels/species are \n {y_permed}")
print(f"The corresponding data rows are \n {X_permed[0:5]}")

The scrambled labels/species are 
 [ 0.  0.  0. ...  0. 56. 28.]
The corresponding data rows are 
 [[0.00e+00 6.00e-02 5.00e-02 2.23e+02 5.60e+00 6.43e+01 3.87e+01 5.14e+01
  6.40e+01 2.40e+01 4.30e+01 2.98e+01 2.40e+00 5.85e+01 5.05e+01 0.00e+00
  2.00e+00]
 [0.00e+00 1.70e-01 0.00e+00 4.56e+02 3.40e+00 7.67e+01 3.83e+01 5.70e+01
  4.50e+01 9.00e+00 2.10e+01 1.79e+01 3.70e+00 8.88e+01 5.26e+01 1.00e+00
  0.00e+00]
 [0.00e+00 1.40e-01 2.00e-02 3.42e+02 7.30e+00 8.90e+01 5.71e+01 7.15e+01
  4.50e+01 1.60e+01 2.80e+01 3.65e+01 3.30e+00 7.89e+01 6.28e+01 4.00e+00
  0.00e+00]
 [0.00e+00 9.00e-02 0.00e+00 2.68e+02 6.00e+00 6.86e+01 4.00e+01 5.19e+01
  8.70e+01 1.80e+01 4.60e+01 3.16e+01 3.70e+00 8.90e+01 5.21e+01 4.00e+00
  9.00e+00]
 [0.00e+00 1.90e-01 3.50e-01 3.24e+02 3.90e+00 6.57e+01 5.09e+01 5.93e+01
  3.20e+01 1.90e+01 2.30e+01 2.11e+01 1.07e+01 2.57e+02 5.27e+01 5.00e+00
  7.00e+00]]


In [214]:
# Seperate data into test data and training data 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2, random_state=42)
print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )


training with 5040 rows;  testing with 1260 rows



## Begin Building the Model

In [215]:
from sklearn import tree      # for decision trees

best_depth = 1   # we don't know what depth to use, so let's guess 1
dtree_model = tree.DecisionTreeClassifier(max_depth=best_depth)

# Let's train the model.   It's this one line:
dtree_model.fit(X_train, y_train)                              # yay!  trained!
print("Created and trained a DT classifier with max depth =", best_depth) 

Created and trained a DT classifier with max depth = 1


In [216]:
# Test the model with the test data 

predicted_labels = dtree_model.predict(X_test)   
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual  labels  :", actual_labels)

# And, some overall results
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"\nResults on test set:  {num_correct} correct out of {total} total.")

Predicted labels: [0. 0. 0. ... 1. 1. 1.]
Actual  labels  : [ 1.  0.  0. ... 26.  1.  1.]

Results on test set:  574 correct out of 1260 total.


In [217]:
# Function to compare labels

def compare_labels(predicted_labels, actual_labels):
    """ a more neatly formatted comparison """
    NUM_LABELS = len(predicted_labels)
    num_correct = 0
    
    for i in range(NUM_LABELS):
        p = int(round(predicted_labels[i]))         # round protects from fp error 
        a = int(round(actual_labels[i]))
        result = "incorrect"
        if p == a:  # if they match,
            result = ""       # no longer incorrect
            num_correct += 1  # and we count a match!

       

    print()
    print("Correct:", num_correct, "out of", NUM_LABELS)
    return num_correct

# let's try it out!
compare_labels(predicted_labels,actual_labels)


Correct: 574 out of 1260


574

In [218]:
#
# Now, let's see the tree!
#

filename = 'tree_data.gv'    # sometimes .dot is used, instead of .gv

tree.export_graphviz(dtree_model, out_file=filename,  # the filename constructed above...!
                            feature_names=COLUMNS[:-1], # actual feature names, not species
                            filled=True,              # fun!
                            rotate=False,             # False for Up/Down; True for L/R
                            class_names=ClassNames,      # good to have   
                            leaves_parallel=True )    # lots of options!

print(f"file {filename} written. Try pasting its contents to  http://viz-js.com/\n")

with open(filename, "r") as f:
    all_file_text = f.read()
    print(all_file_text)
    
#
# Lab task:  build trees at depths 1 and 2+ (submit in this notebook -- see next cell for depth-1 solution)
#

file tree_data.gv written. Try pasting its contents to  http://viz-js.com/

digraph Tree {
node [shape=box, style="filled", color="black"] ;
graph [ranksep=equally, splines=polyline] ;
0 [label="ZoneNum <= 4.5\ngini = 0.829\nsamples = 5040\nvalue = [1948, 649, 176, 133, 31, 27, 29, 32, 57, 43, 36\n55, 21, 15, 25, 39, 53, 25, 19, 21, 20, 40, 41\n45, 48, 49, 63, 45, 40, 42, 39, 29, 33, 44, 41\n43, 26, 25, 32, 36, 33, 31, 32, 36, 28, 23, 32\n23, 19, 19, 16, 14, 17, 24, 17, 28, 20, 21, 28\n24, 28, 13, 9, 13, 16, 11, 11, 17, 14, 6, 10\n7, 5, 10, 8, 5, 2, 4, 2, 6, 5, 10, 4, 10, 6\n9, 7, 7, 10, 9, 15, 11, 4, 11, 6, 8, 3, 1, 3\n2, 1, 1]\nclass = 0", fillcolor="#f7dac4"] ;
1 [label="gini = 0.231\nsamples = 2098\nvalue = [1818, 280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 

In [219]:

# Use cross validation to compare different tree-depths

from sklearn.model_selection import cross_val_score

#
# cross-validation splits the training set into two pieces:
#   + model-building and model-validation. We'll use "build" and "validate"
#

best_d = 1
best_accuracy = 0.0

for d in range(1,20):
    cv_model = tree.DecisionTreeClassifier(max_depth=d)   # for each depth, d
    cv_scores = cross_val_score( cv_model, X_train, y_train, cv=5 ) # 5 means 80/20 split
    # print(cv_scores)  # we usually don't want to see the five individual scores 
    average_cv_accuracy = cv_scores.mean()  # more likely, only their average
    print(f"depth: {d:2d}  cv accuracy: {average_cv_accuracy:7.4f}")
    
    if average_cv_accuracy > best_accuracy:
        best_accuracy = average_cv_accuracy
        best_d = d

    
    
# assign best value of d to best_depth
best_depth = best_d   # may have to hand-tune this, depending on what happens...
print()
print(f"best_depth = {best_depth} is our choice for an underfitting/overfitting balance.")  

depth:  1  cv accuracy:  0.4339


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth:  2  cv accuracy:  0.4528
depth:  3  cv accuracy:  0.4740
depth:  4  cv accuracy:  0.5095


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth:  5  cv accuracy:  0.5540
depth:  6  cv accuracy:  0.5647


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth:  7  cv accuracy:  0.5740
depth:  8  cv accuracy:  0.5843


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth:  9  cv accuracy:  0.5897
depth: 10  cv accuracy:  0.5865


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth: 11  cv accuracy:  0.5859


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth: 12  cv accuracy:  0.5897


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth: 13  cv accuracy:  0.5823


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth: 14  cv accuracy:  0.5839


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth: 15  cv accuracy:  0.5812


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth: 16  cv accuracy:  0.5810


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth: 17  cv accuracy:  0.5817


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth: 18  cv accuracy:  0.5867


/Users/jenniferzecena/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


depth: 19  cv accuracy:  0.5831

best_depth = 12 is our choice for an underfitting/overfitting balance.


In [220]:
# Use the best Depth to build a new model 

from sklearn import tree      # for decision trees

# we should have best_depth from our cv exploration
dtree_model_tuned = tree.DecisionTreeClassifier(max_depth=8)

# we train the model (it's one line!)
dtree_model_tuned.fit(X_train, y_train)                              # yay!  trained!
print("Created and trained a DT classifier with max depth =", best_depth) 

Created and trained a DT classifier with max depth = 12


In [221]:
#
# Re-create and re-run the  "Model-testing Cell"     How does it do with best_k?!
#
predicted_labels = dtree_model_tuned.predict(X_test)
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual labels:", actual_labels)
print()

# and, we'll print our nicer table...
compare_labels(predicted_labels,actual_labels)

Predicted labels: [ 1.  0.  0. ... 26.  1.  1.]
Actual labels: [ 1.  0.  0. ... 26.  1.  1.]


Correct: 744 out of 1260


744

In [222]:
#
# Now, let's see the tree!
#

filename = 'tree_data.gv'    # sometimes .dot is used, instead of .gv

tree.export_graphviz(dtree_model_tuned, out_file=filename,  # the filename constructed above...!
                            feature_names=COLUMNS[:-1], # actual feature names, not species
                            filled=True,              # fun!
                            rotate=False,             # False for Up/Down; True for L/R
                            class_names=ClassNames,      # good to have   
                            leaves_parallel=True )    # lots of options!

print(f"file {filename} written. Try pasting its contents to  http://viz-js.com/\n")

with open(filename, "r") as f:
    all_file_text = f.read()
    print(all_file_text)
    

file tree_data.gv written. Try pasting its contents to  http://viz-js.com/

digraph Tree {
node [shape=box, style="filled", color="black"] ;
graph [ranksep=equally, splines=polyline] ;
0 [label="ZoneNum <= 4.5\ngini = 0.829\nsamples = 5040\nvalue = [1948, 649, 176, 133, 31, 27, 29, 32, 57, 43, 36\n55, 21, 15, 25, 39, 53, 25, 19, 21, 20, 40, 41\n45, 48, 49, 63, 45, 40, 42, 39, 29, 33, 44, 41\n43, 26, 25, 32, 36, 33, 31, 32, 36, 28, 23, 32\n23, 19, 19, 16, 14, 17, 24, 17, 28, 20, 21, 28\n24, 28, 13, 9, 13, 16, 11, 11, 17, 14, 6, 10\n7, 5, 10, 8, 5, 2, 4, 2, 6, 5, 10, 4, 10, 6\n9, 7, 7, 10, 9, 15, 11, 4, 11, 6, 8, 3, 1, 3\n2, 1, 1]\nclass = 0", fillcolor="#f7dac4"] ;
1 [label="Avg Soil Temp (F) <= 67.15\ngini = 0.231\nsamples = 2098\nvalue = [1818, 280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [223]:
#
# Ok!  We have tuned our DT to use the "best" depth...
#
# Now, we use ALL available data to train our final predictive model:
#

from sklearn import tree      # for decision trees

# we should have best_depth from our cv exploration
dtree_model_final = tree.DecisionTreeClassifier(max_depth=best_depth)

# we train the model (it's one line!)
dtree_model_final.fit(X_all, y_all)                              # yay!  trained!
print("Created and trained a 'final' DT classifier with max depth =", best_depth) 

Created and trained a 'final' DT classifier with max depth = 12


In [224]:
#
# final predictive model (k-nearest-neighbor), with tuned k + ALL data incorporated
#

def predictive_model( Features ):
    """ input: a list of four features 
                [ sepallen, sepalwid, petallen, petalwid ]
        output: the predicted species of iris, from
                  setosa (0), versicolor (1), virginica (2)
    """
    our_features = np.asarray([Features])                 # extra brackets needed
    predicted_species = dtree_model_final.predict(our_features)
    
    predicted_species = int(round(predicted_species[0]))  # unpack one element
    return f"({predicted_species})"
    
#
# Try it!
# 
# Features = eval(input("Enter new Features: "))
#
Features = [0, 0.19, 0.00, 470, 13.2, 93.5, 60.6, 76.0, 76, 21, 43, 52.0, 3.1, 75.2, 73.2, 0, 0]
# result = predictive_model( Features )
print(f"I predict {result} from Features {Features}")

I predict (0) from Features [0, 0.19, 0.0, 470, 13.2, 93.5, 60.6, 76.0, 76, 21, 43, 52.0, 3.1, 75.2, 73.2, 0, 0]


In [225]:
#
# feature importances!

print(dtree_model_final.feature_importances_)
print()

# let's see them with each feature name:
IMPs = dtree_model_final.feature_importances_

# enumerate is great when you want indices _and_ elements!
for i, importance in enumerate(IMPs):
    perc = importance*100
    print(f"Feature {COLUMNS[i]:>12s} has {perc:>7.2f}% of the decision-making importance.")

[0.00218607 0.02523726 0.00629356 0.04478657 0.01495529 0.03903685
 0.02705742 0.07251042 0.02683472 0.01944446 0.02312176 0.01427971
 0.01197595 0.02375273 0.12976596 0.01667408 0.5020872 ]

Feature      Holiday has    0.22% of the decision-making importance.
Feature     ETo (in) has    2.52% of the decision-making importance.
Feature  Precip (in) has    0.63% of the decision-making importance.
Feature Sol Rad (Ly/day) has    4.48% of the decision-making importance.
Feature Avg Vap Pres (mBars) has    1.50% of the decision-making importance.
Feature Max Air Temp (F) has    3.90% of the decision-making importance.
Feature Min Air Temp (F) has    2.71% of the decision-making importance.
Feature Avg Air Temp (F) has    7.25% of the decision-making importance.
Feature Max Rel Hum (%) has    2.68% of the decision-making importance.
Feature Min Rel Hum (%) has    1.94% of the decision-making importance.
Feature Avg Rel Hum (%) has    2.31% of the decision-making importance.
Feature Dew Poin